# Generated by Django 3.2.6 on 2022-01-02 13:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=50)),
                ('user_id', models.CharField(max_length=50)),
                ('pw', models.TextField(max_length=500)),
                ('birthday', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, max_length=2, null=True)),
                ('watch_time', models.TimeField(blank=True, null=True)),
                ('job', models.CharField(blank=True, max_length=50, null=True)),
                ('region', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Prefer_ott_content_genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prefer_genre_1', models.CharField(max_length=50)),
                ('prefer_genre_2', models.CharField(max_length=50)),
                ('prefer_genre_3', models.CharField(max_length=50)),
                ('prefer_genre_4', models.CharField(max_length=50)),
                ('prefer_genre_5', models.CharField(max_length=50)),
                ('prefer_genre_6', models.CharField(max_length=50)),
                ('prefer_genre_7', models.CharField(max_length=50)),
                ('prefer_genre_8', models.CharField(max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prefer_ott_content', to='user.user')),
            ],
        ),
    ]
