# Generated by Django 3.2.6 on 2021-12-30 07:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(default='', max_length=2),
        ),
        migrations.AddField(
            model_name='user',
            name='job',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='user',
            name='region',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.CreateModel(
            name='Prefer_ott_content_genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prefer_genre_1', models.CharField(max_length=50)),
                ('prefer_genre_2', models.CharField(max_length=50)),
                ('prefer_genre_3', models.CharField(max_length=50)),
                ('prefer_genre_4', models.CharField(max_length=50)),
                ('prefer_genre_5', models.CharField(max_length=50)),
                ('prefer_genre_6', models.CharField(max_length=50)),
                ('prefer_genre_7', models.CharField(max_length=50)),
                ('prefer_genre_8', models.CharField(max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prefer_ott_content', to='user.user')),
            ],
        ),
    ]
