# Generated by Django 3.2.6 on 2022-01-04 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('small_theater', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='smalltheater',
            name='theater_genre2',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='smalltheater',
            name='theater_genre1',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
