# Generated by Django 3.2.6 on 2022-01-08 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_genre', models.CharField(default='', max_length=20, null=True)),
                ('average_male', models.FloatField(default=0.01)),
                ('average_female', models.FloatField(default=0.01)),
                ('average_10s', models.FloatField(default=0.01)),
                ('average_20s', models.FloatField(default=0.01)),
                ('average_30s', models.FloatField(default=0.01)),
                ('average_40s', models.FloatField(default=0.01)),
                ('average_50_up', models.FloatField(default=0.01)),
            ],
        ),
        migrations.CreateModel(
            name='ReviewScoreT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('people', models.CharField(default='', max_length=40, null=True)),
                ('drama', models.FloatField(default=0.01)),
                ('comedy', models.FloatField(default=0.01)),
                ('action', models.FloatField(default=0.01)),
                ('thriller', models.FloatField(default=0.01)),
                ('romance', models.FloatField(default=0.01)),
                ('crime', models.FloatField(default=0.01)),
                ('adventure', models.FloatField(default=0.01)),
                ('animation', models.FloatField(default=0.01)),
                ('fantasy', models.FloatField(default=0.01)),
                ('family', models.FloatField(default=0.01)),
                ('sci_fi', models.FloatField(default=0.01)),
                ('mystery', models.FloatField(default=0.01)),
                ('horror', models.FloatField(default=0.01)),
                ('documentary', models.FloatField(default=0.01)),
                ('biography', models.FloatField(default=0.01)),
                ('history', models.FloatField(default=0.01)),
                ('music', models.FloatField(default=0.01)),
                ('short', models.FloatField(default=0.01)),
                ('sport', models.FloatField(default=0.01)),
                ('war', models.FloatField(default=0.01)),
                ('musical', models.FloatField(default=0.01)),
                ('western', models.FloatField(default=0.01)),
            ],
        ),
    ]
