# Generated by Django 3.2.6 on 2021-12-30 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=50)),
                ('user_id', models.CharField(max_length=50)),
                ('pw', models.TextField(max_length=500)),
            ],
        ),
    ]
