# Generated by Django 3.2.6 on 2022-01-03 06:06

import apps.user.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prefer_ott_content_genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prefer_genre_1', models.CharField(max_length=50)),
                ('prefer_genre_2', models.CharField(max_length=50)),
                ('prefer_genre_3', models.CharField(max_length=50)),
                ('prefer_genre_4', models.CharField(max_length=50)),
                ('prefer_genre_5', models.CharField(max_length=50)),
                ('prefer_genre_6', models.CharField(max_length=50)),
                ('prefer_genre_7', models.CharField(max_length=50)),
                ('prefer_genre_8', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('nickname', models.CharField(max_length=50, unique=True, validators=[apps.user.validators.UserNameValidator()], verbose_name='닉네임')),
                ('user_id', models.CharField(max_length=50, unique=True)),
                ('birthday', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, max_length=2, null=True)),
                ('watch_time', models.IntegerField(blank=True, null=True)),
                ('job', models.CharField(blank=True, max_length=50, null=True)),
                ('region', models.CharField(blank=True, max_length=50, null=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('prefer_ott_content_genre', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='user.prefer_ott_content_genre')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'user',
            },
        ),
    ]
