# Generated by Django 3.2.6 on 2022-01-03 15:40

import apps.user.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_user_prefer_ott_content_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='nickname',
            field=models.CharField(blank=True, max_length=50, null=True, validators=[apps.user.validators.UserNameValidator()], verbose_name='닉네임'),
        ),
    ]
