# Generated by Django 3.2.6 on 2022-01-06 02:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20220106_0009'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='preferottcontentgenre',
            name='user',
        ),
    ]
