# Generated by Django 3.2.6 on 2022-01-06 04:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_remove_preferottcontentgenre_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='preferottcontentgenre',
            old_name='document',
            new_name='documentary',
        ),
    ]
