# Generated by Django 3.2.6 on 2022-01-06 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_auto_20220106_1827'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='prefer_ott_content_genres',
            field=models.ManyToManyField(to='user.PreferOttContentGenre'),
        ),
    ]
